name: automation go to docker

on: 
  workflow_dispatch:

jobs:
  build_and_push_to_docker:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: buil part to docker    
        run: docker build -t karush/go-training/helloworld .
      - name: push to docker hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          reposytory: karush/go
          tags: latest, ${{ github.run_number }}

