# name: hellow_go 
# on:
#   workflow_dispatch:
#     inputs:
   
#       environment:
#         description: 'choise go version'
#         required: true
#         options:
#         - 1.19.1
#         - 1.18
#         - 1.19.2

# jobs:
#   log-the-inputs:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Log level: $LEVEL"
#           echo "Tags: $TAGS"
#           echo "Environment: $ENVIRONMENT"
#         env:
         
#           ENVIRONMENT: ${{ inputs.environment }}
name: go hello world 

on:
  workflow_dispatch:
    inputs:
      version_go:
        description: 'go version'
        required: true
        default: '1.18'
        type: choice
        options:
        - 1.19.1
        - 1.18.0
        - 1.19.2

jobs:
  Hello:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform}}

    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.version_go}}
          
      - uses: actions/checkout@v3

      - name: Run go file
        run: go run main.go

      # - name: Build
      #   run: go build -v ./...

      # - name: Test
      #   run: go test -v ./...
